/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.AlarmDefinitionSeverityRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmDefinitionSeverity extends TableImpl<AlarmDefinitionSeverityRecord> {

	private static final long serialVersionUID = -290445965;

	/**
	 * The reference instance of <code>mon.alarm_definition_severity</code>
	 */
	public static final AlarmDefinitionSeverity ALARM_DEFINITION_SEVERITY = new AlarmDefinitionSeverity();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlarmDefinitionSeverityRecord> getRecordType() {
		return AlarmDefinitionSeverityRecord.class;
	}

	/**
	 * The column <code>mon.alarm_definition_severity.name</code>.
	 */
	public final TableField<AlarmDefinitionSeverityRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>mon.alarm_definition_severity</code> table reference
	 */
	public AlarmDefinitionSeverity() {
		this("alarm_definition_severity", null);
	}

	/**
	 * Create an aliased <code>mon.alarm_definition_severity</code> table reference
	 */
	public AlarmDefinitionSeverity(String alias) {
		this(alias, ALARM_DEFINITION_SEVERITY);
	}

	private AlarmDefinitionSeverity(String alias, Table<AlarmDefinitionSeverityRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlarmDefinitionSeverity(String alias, Table<AlarmDefinitionSeverityRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlarmDefinitionSeverityRecord> getPrimaryKey() {
		return Keys.KEY_ALARM_DEFINITION_SEVERITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlarmDefinitionSeverityRecord>> getKeys() {
		return Arrays.<UniqueKey<AlarmDefinitionSeverityRecord>>asList(Keys.KEY_ALARM_DEFINITION_SEVERITY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionSeverity as(String alias) {
		return new AlarmDefinitionSeverity(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AlarmDefinitionSeverity rename(String name) {
		return new AlarmDefinitionSeverity(name, null);
	}
}
