/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.AlarmMetricRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmMetric extends TableImpl<AlarmMetricRecord> {

	private static final long serialVersionUID = -1142307702;

	/**
	 * The reference instance of <code>mon.alarm_metric</code>
	 */
	public static final AlarmMetric ALARM_METRIC = new AlarmMetric();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlarmMetricRecord> getRecordType() {
		return AlarmMetricRecord.class;
	}

	/**
	 * The column <code>mon.alarm_metric.alarm_id</code>.
	 */
	public final TableField<AlarmMetricRecord, String> ALARM_ID = createField("alarm_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_metric.metric_definition_dimensions_id</code>.
	 */
	public final TableField<AlarmMetricRecord, byte[]> METRIC_DEFINITION_DIMENSIONS_ID = createField("metric_definition_dimensions_id", org.jooq.impl.SQLDataType.BINARY.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mon.alarm_metric</code> table reference
	 */
	public AlarmMetric() {
		this("alarm_metric", null);
	}

	/**
	 * Create an aliased <code>mon.alarm_metric</code> table reference
	 */
	public AlarmMetric(String alias) {
		this(alias, ALARM_METRIC);
	}

	private AlarmMetric(String alias, Table<AlarmMetricRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlarmMetric(String alias, Table<AlarmMetricRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlarmMetricRecord> getPrimaryKey() {
		return Keys.KEY_ALARM_METRIC_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlarmMetricRecord>> getKeys() {
		return Arrays.<UniqueKey<AlarmMetricRecord>>asList(Keys.KEY_ALARM_METRIC_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AlarmMetricRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AlarmMetricRecord, ?>>asList(Keys.FK_ALARM_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmMetric as(String alias) {
		return new AlarmMetric(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AlarmMetric rename(String name) {
		return new AlarmMetric(name, null);
	}
}
