/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.AlarmRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alarm extends TableImpl<AlarmRecord> {

	private static final long serialVersionUID = -1580812835;

	/**
	 * The reference instance of <code>mon.alarm</code>
	 */
	public static final Alarm ALARM = new Alarm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlarmRecord> getRecordType() {
		return AlarmRecord.class;
	}

	/**
	 * The column <code>mon.alarm.id</code>.
	 */
	public final TableField<AlarmRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm.alarm_definition_id</code>.
	 */
	public final TableField<AlarmRecord, String> ALARM_DEFINITION_ID = createField("alarm_definition_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.alarm.state</code>.
	 */
	public final TableField<AlarmRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm.lifecycle_state</code>.
	 */
	public final TableField<AlarmRecord, String> LIFECYCLE_STATE = createField("lifecycle_state", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>mon.alarm.link</code>.
	 */
	public final TableField<AlarmRecord, String> LINK = createField("link", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>mon.alarm.created_at</code>.
	 */
	public final TableField<AlarmRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.alarm.state_updated_at</code>.
	 */
	public final TableField<AlarmRecord, Timestamp> STATE_UPDATED_AT = createField("state_updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>mon.alarm.updated_at</code>.
	 */
	public final TableField<AlarmRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>mon.alarm</code> table reference
	 */
	public Alarm() {
		this("alarm", null);
	}

	/**
	 * Create an aliased <code>mon.alarm</code> table reference
	 */
	public Alarm(String alias) {
		this(alias, ALARM);
	}

	private Alarm(String alias, Table<AlarmRecord> aliased) {
		this(alias, aliased, null);
	}

	private Alarm(String alias, Table<AlarmRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlarmRecord> getPrimaryKey() {
		return Keys.KEY_ALARM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlarmRecord>> getKeys() {
		return Arrays.<UniqueKey<AlarmRecord>>asList(Keys.KEY_ALARM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Alarm as(String alias) {
		return new Alarm(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Alarm rename(String name) {
		return new Alarm(name, null);
	}
}
