/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.AlarmDefinitionRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmDefinition extends TableImpl<AlarmDefinitionRecord> {

	private static final long serialVersionUID = -1180747523;

	/**
	 * The reference instance of <code>mon.alarm_definition</code>
	 */
	public static final AlarmDefinition ALARM_DEFINITION = new AlarmDefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlarmDefinitionRecord> getRecordType() {
		return AlarmDefinitionRecord.class;
	}

	/**
	 * The column <code>mon.alarm_definition.id</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_definition.tenant_id</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_definition.name</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.alarm_definition.description</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mon.alarm_definition.expression</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> EXPRESSION = createField("expression", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_definition.severity</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> SEVERITY = createField("severity", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_definition.match_by</code>.
	 */
	public final TableField<AlarmDefinitionRecord, String> MATCH_BY = createField("match_by", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * The column <code>mon.alarm_definition.actions_enabled</code>.
	 */
	public final TableField<AlarmDefinitionRecord, Boolean> ACTIONS_ENABLED = createField("actions_enabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.alarm_definition.created_at</code>.
	 */
	public final TableField<AlarmDefinitionRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_definition.updated_at</code>.
	 */
	public final TableField<AlarmDefinitionRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_definition.deleted_at</code>.
	 */
	public final TableField<AlarmDefinitionRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>mon.alarm_definition</code> table reference
	 */
	public AlarmDefinition() {
		this("alarm_definition", null);
	}

	/**
	 * Create an aliased <code>mon.alarm_definition</code> table reference
	 */
	public AlarmDefinition(String alias) {
		this(alias, ALARM_DEFINITION);
	}

	private AlarmDefinition(String alias, Table<AlarmDefinitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlarmDefinition(String alias, Table<AlarmDefinitionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlarmDefinitionRecord> getPrimaryKey() {
		return Keys.KEY_ALARM_DEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlarmDefinitionRecord>> getKeys() {
		return Arrays.<UniqueKey<AlarmDefinitionRecord>>asList(Keys.KEY_ALARM_DEFINITION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinition as(String alias) {
		return new AlarmDefinition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AlarmDefinition rename(String name) {
		return new AlarmDefinition(name, null);
	}
}
