/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.AlarmActionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmAction extends TableImpl<AlarmActionRecord> {

	private static final long serialVersionUID = -603153434;

	/**
	 * The reference instance of <code>mon.alarm_action</code>
	 */
	public static final AlarmAction ALARM_ACTION = new AlarmAction();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlarmActionRecord> getRecordType() {
		return AlarmActionRecord.class;
	}

	/**
	 * The column <code>mon.alarm_action.alarm_definition_id</code>.
	 */
	public final TableField<AlarmActionRecord, String> ALARM_DEFINITION_ID = createField("alarm_definition_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_action.alarm_state</code>.
	 */
	public final TableField<AlarmActionRecord, String> ALARM_STATE = createField("alarm_state", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>mon.alarm_action.action_id</code>.
	 */
	public final TableField<AlarmActionRecord, String> ACTION_ID = createField("action_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * Create a <code>mon.alarm_action</code> table reference
	 */
	public AlarmAction() {
		this("alarm_action", null);
	}

	/**
	 * Create an aliased <code>mon.alarm_action</code> table reference
	 */
	public AlarmAction(String alias) {
		this(alias, ALARM_ACTION);
	}

	private AlarmAction(String alias, Table<AlarmActionRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlarmAction(String alias, Table<AlarmActionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlarmActionRecord> getPrimaryKey() {
		return Keys.KEY_ALARM_ACTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlarmActionRecord>> getKeys() {
		return Arrays.<UniqueKey<AlarmActionRecord>>asList(Keys.KEY_ALARM_ACTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AlarmActionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AlarmActionRecord, ?>>asList(Keys.FK_ALARM_ACTION_NOTIFICATION_METHOD_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmAction as(String alias) {
		return new AlarmAction(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AlarmAction rename(String name) {
		return new AlarmAction(name, null);
	}
}
