/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.AlarmStateRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmState extends TableImpl<AlarmStateRecord> {

	private static final long serialVersionUID = -817436746;

	/**
	 * The reference instance of <code>mon.alarm_state</code>
	 */
	public static final AlarmState ALARM_STATE = new AlarmState();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlarmStateRecord> getRecordType() {
		return AlarmStateRecord.class;
	}

	/**
	 * The column <code>mon.alarm_state.name</code>.
	 */
	public final TableField<AlarmStateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>mon.alarm_state</code> table reference
	 */
	public AlarmState() {
		this("alarm_state", null);
	}

	/**
	 * Create an aliased <code>mon.alarm_state</code> table reference
	 */
	public AlarmState(String alias) {
		this(alias, ALARM_STATE);
	}

	private AlarmState(String alias, Table<AlarmStateRecord> aliased) {
		this(alias, aliased, null);
	}

	private AlarmState(String alias, Table<AlarmStateRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlarmStateRecord> getPrimaryKey() {
		return Keys.KEY_ALARM_STATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlarmStateRecord>> getKeys() {
		return Arrays.<UniqueKey<AlarmStateRecord>>asList(Keys.KEY_ALARM_STATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmState as(String alias) {
		return new AlarmState(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AlarmState rename(String name) {
		return new AlarmState(name, null);
	}
}
