/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.EventTransformRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventTransform extends TableImpl<EventTransformRecord> {

	private static final long serialVersionUID = -297238599;

	/**
	 * The reference instance of <code>mon.event_transform</code>
	 */
	public static final EventTransform EVENT_TRANSFORM = new EventTransform();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EventTransformRecord> getRecordType() {
		return EventTransformRecord.class;
	}

	/**
	 * The column <code>mon.event_transform.id</code>.
	 */
	public final TableField<EventTransformRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.tenant_id</code>.
	 */
	public final TableField<EventTransformRecord, String> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.name</code>.
	 */
	public final TableField<EventTransformRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.description</code>.
	 */
	public final TableField<EventTransformRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.specification</code>.
	 */
	public final TableField<EventTransformRecord, String> SPECIFICATION = createField("specification", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.enabled</code>.
	 */
	public final TableField<EventTransformRecord, Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>mon.event_transform.created_at</code>.
	 */
	public final TableField<EventTransformRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.updated_at</code>.
	 */
	public final TableField<EventTransformRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.event_transform.deleted_at</code>.
	 */
	public final TableField<EventTransformRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>mon.event_transform</code> table reference
	 */
	public EventTransform() {
		this("event_transform", null);
	}

	/**
	 * Create an aliased <code>mon.event_transform</code> table reference
	 */
	public EventTransform(String alias) {
		this(alias, EVENT_TRANSFORM);
	}

	private EventTransform(String alias, Table<EventTransformRecord> aliased) {
		this(alias, aliased, null);
	}

	private EventTransform(String alias, Table<EventTransformRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EventTransformRecord> getPrimaryKey() {
		return Keys.KEY_EVENT_TRANSFORM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EventTransformRecord>> getKeys() {
		return Arrays.<UniqueKey<EventTransformRecord>>asList(Keys.KEY_EVENT_TRANSFORM_PRIMARY, Keys.KEY_EVENT_TRANSFORM_TENANT_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransform as(String alias) {
		return new EventTransform(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EventTransform rename(String name) {
		return new EventTransform(name, null);
	}
}
