/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.MetricDefinitionDimensionsRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricDefinitionDimensions extends TableImpl<MetricDefinitionDimensionsRecord> {

	private static final long serialVersionUID = 2079048479;

	/**
	 * The reference instance of <code>mon.metric_definition_dimensions</code>
	 */
	public static final MetricDefinitionDimensions METRIC_DEFINITION_DIMENSIONS = new MetricDefinitionDimensions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MetricDefinitionDimensionsRecord> getRecordType() {
		return MetricDefinitionDimensionsRecord.class;
	}

	/**
	 * The column <code>mon.metric_definition_dimensions.id</code>.
	 */
	public final TableField<MetricDefinitionDimensionsRecord, byte[]> ID = createField("id", org.jooq.impl.SQLDataType.BINARY.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.metric_definition_dimensions.metric_definition_id</code>.
	 */
	public final TableField<MetricDefinitionDimensionsRecord, byte[]> METRIC_DEFINITION_ID = createField("metric_definition_id", org.jooq.impl.SQLDataType.BINARY.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.metric_definition_dimensions.metric_dimension_set_id</code>.
	 */
	public final TableField<MetricDefinitionDimensionsRecord, byte[]> METRIC_DIMENSION_SET_ID = createField("metric_dimension_set_id", org.jooq.impl.SQLDataType.BINARY.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mon.metric_definition_dimensions</code> table reference
	 */
	public MetricDefinitionDimensions() {
		this("metric_definition_dimensions", null);
	}

	/**
	 * Create an aliased <code>mon.metric_definition_dimensions</code> table reference
	 */
	public MetricDefinitionDimensions(String alias) {
		this(alias, METRIC_DEFINITION_DIMENSIONS);
	}

	private MetricDefinitionDimensions(String alias, Table<MetricDefinitionDimensionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private MetricDefinitionDimensions(String alias, Table<MetricDefinitionDimensionsRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MetricDefinitionDimensionsRecord> getPrimaryKey() {
		return Keys.KEY_METRIC_DEFINITION_DIMENSIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MetricDefinitionDimensionsRecord>> getKeys() {
		return Arrays.<UniqueKey<MetricDefinitionDimensionsRecord>>asList(Keys.KEY_METRIC_DEFINITION_DIMENSIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionDimensions as(String alias) {
		return new MetricDefinitionDimensions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MetricDefinitionDimensions rename(String name) {
		return new MetricDefinitionDimensions(name, null);
	}
}
