/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.MetricDefinitionRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricDefinition extends TableImpl<MetricDefinitionRecord> {

	private static final long serialVersionUID = -617885020;

	/**
	 * The reference instance of <code>mon.metric_definition</code>
	 */
	public static final MetricDefinition METRIC_DEFINITION = new MetricDefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MetricDefinitionRecord> getRecordType() {
		return MetricDefinitionRecord.class;
	}

	/**
	 * The column <code>mon.metric_definition.id</code>.
	 */
	public final TableField<MetricDefinitionRecord, byte[]> ID = createField("id", org.jooq.impl.SQLDataType.BINARY.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.metric_definition.name</code>.
	 */
	public final TableField<MetricDefinitionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>mon.metric_definition.tenant_id</code>.
	 */
	public final TableField<MetricDefinitionRecord, String> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.metric_definition.region</code>.
	 */
	public final TableField<MetricDefinitionRecord, String> REGION = createField("region", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mon.metric_definition</code> table reference
	 */
	public MetricDefinition() {
		this("metric_definition", null);
	}

	/**
	 * Create an aliased <code>mon.metric_definition</code> table reference
	 */
	public MetricDefinition(String alias) {
		this(alias, METRIC_DEFINITION);
	}

	private MetricDefinition(String alias, Table<MetricDefinitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private MetricDefinition(String alias, Table<MetricDefinitionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MetricDefinitionRecord> getPrimaryKey() {
		return Keys.KEY_METRIC_DEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MetricDefinitionRecord>> getKeys() {
		return Arrays.<UniqueKey<MetricDefinitionRecord>>asList(Keys.KEY_METRIC_DEFINITION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinition as(String alias) {
		return new MetricDefinition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MetricDefinition rename(String name) {
		return new MetricDefinition(name, null);
	}
}
