/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.MetricDimensionRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * PRIMARY KEY (`id`)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricDimension extends TableImpl<MetricDimensionRecord> {

	private static final long serialVersionUID = -583741646;

	/**
	 * The reference instance of <code>mon.metric_dimension</code>
	 */
	public static final MetricDimension METRIC_DIMENSION = new MetricDimension();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MetricDimensionRecord> getRecordType() {
		return MetricDimensionRecord.class;
	}

	/**
	 * The column <code>mon.metric_dimension.dimension_set_id</code>.
	 */
	public final TableField<MetricDimensionRecord, byte[]> DIMENSION_SET_ID = createField("dimension_set_id", org.jooq.impl.SQLDataType.BINARY.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.metric_dimension.name</code>.
	 */
	public final TableField<MetricDimensionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.metric_dimension.value</code>.
	 */
	public final TableField<MetricDimensionRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mon.metric_dimension</code> table reference
	 */
	public MetricDimension() {
		this("metric_dimension", null);
	}

	/**
	 * Create an aliased <code>mon.metric_dimension</code> table reference
	 */
	public MetricDimension(String alias) {
		this(alias, METRIC_DIMENSION);
	}

	private MetricDimension(String alias, Table<MetricDimensionRecord> aliased) {
		this(alias, aliased, null);
	}

	private MetricDimension(String alias, Table<MetricDimensionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "PRIMARY KEY (`id`)");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MetricDimensionRecord>> getKeys() {
		return Arrays.<UniqueKey<MetricDimensionRecord>>asList(Keys.KEY_METRIC_DIMENSION_METRIC_DIMENSION_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDimension as(String alias) {
		return new MetricDimension(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MetricDimension rename(String name) {
		return new MetricDimension(name, null);
	}
}
