/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.NotificationMethodTypeRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationMethodType extends TableImpl<NotificationMethodTypeRecord> {

	private static final long serialVersionUID = -785104797;

	/**
	 * The reference instance of <code>mon.notification_method_type</code>
	 */
	public static final NotificationMethodType NOTIFICATION_METHOD_TYPE = new NotificationMethodType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NotificationMethodTypeRecord> getRecordType() {
		return NotificationMethodTypeRecord.class;
	}

	/**
	 * The column <code>mon.notification_method_type.name</code>.
	 */
	public final TableField<NotificationMethodTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>mon.notification_method_type</code> table reference
	 */
	public NotificationMethodType() {
		this("notification_method_type", null);
	}

	/**
	 * Create an aliased <code>mon.notification_method_type</code> table reference
	 */
	public NotificationMethodType(String alias) {
		this(alias, NOTIFICATION_METHOD_TYPE);
	}

	private NotificationMethodType(String alias, Table<NotificationMethodTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotificationMethodType(String alias, Table<NotificationMethodTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NotificationMethodTypeRecord> getPrimaryKey() {
		return Keys.KEY_NOTIFICATION_METHOD_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NotificationMethodTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<NotificationMethodTypeRecord>>asList(Keys.KEY_NOTIFICATION_METHOD_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodType as(String alias) {
		return new NotificationMethodType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public NotificationMethodType rename(String name) {
		return new NotificationMethodType(name, null);
	}
}
