/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.NotificationMethodRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationMethod extends TableImpl<NotificationMethodRecord> {

	private static final long serialVersionUID = -1590200223;

	/**
	 * The reference instance of <code>mon.notification_method</code>
	 */
	public static final NotificationMethod NOTIFICATION_METHOD = new NotificationMethod();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NotificationMethodRecord> getRecordType() {
		return NotificationMethodRecord.class;
	}

	/**
	 * The column <code>mon.notification_method.id</code>.
	 */
	public final TableField<NotificationMethodRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.notification_method.tenant_id</code>.
	 */
	public final TableField<NotificationMethodRecord, String> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.notification_method.name</code>.
	 */
	public final TableField<NotificationMethodRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>mon.notification_method.type</code>.
	 */
	public final TableField<NotificationMethodRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>mon.notification_method.address</code>.
	 */
	public final TableField<NotificationMethodRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>mon.notification_method.created_at</code>.
	 */
	public final TableField<NotificationMethodRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.notification_method.updated_at</code>.
	 */
	public final TableField<NotificationMethodRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>mon.notification_method</code> table reference
	 */
	public NotificationMethod() {
		this("notification_method", null);
	}

	/**
	 * Create an aliased <code>mon.notification_method</code> table reference
	 */
	public NotificationMethod(String alias) {
		this(alias, NOTIFICATION_METHOD);
	}

	private NotificationMethod(String alias, Table<NotificationMethodRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotificationMethod(String alias, Table<NotificationMethodRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NotificationMethodRecord> getPrimaryKey() {
		return Keys.KEY_NOTIFICATION_METHOD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NotificationMethodRecord>> getKeys() {
		return Arrays.<UniqueKey<NotificationMethodRecord>>asList(Keys.KEY_NOTIFICATION_METHOD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethod as(String alias) {
		return new NotificationMethod(alias, this);
	}

	/**
	 * Rename this table
	 */
	public NotificationMethod rename(String name) {
		return new NotificationMethod(name, null);
	}
}
