/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.SchemaMigrationsRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaMigrations extends TableImpl<SchemaMigrationsRecord> {

	private static final long serialVersionUID = 1379298006;

	/**
	 * The reference instance of <code>mon.schema_migrations</code>
	 */
	public static final SchemaMigrations SCHEMA_MIGRATIONS = new SchemaMigrations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SchemaMigrationsRecord> getRecordType() {
		return SchemaMigrationsRecord.class;
	}

	/**
	 * The column <code>mon.schema_migrations.version</code>.
	 */
	public final TableField<SchemaMigrationsRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>mon.schema_migrations</code> table reference
	 */
	public SchemaMigrations() {
		this("schema_migrations", null);
	}

	/**
	 * Create an aliased <code>mon.schema_migrations</code> table reference
	 */
	public SchemaMigrations(String alias) {
		this(alias, SCHEMA_MIGRATIONS);
	}

	private SchemaMigrations(String alias, Table<SchemaMigrationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private SchemaMigrations(String alias, Table<SchemaMigrationsRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SchemaMigrationsRecord>> getKeys() {
		return Arrays.<UniqueKey<SchemaMigrationsRecord>>asList(Keys.KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaMigrations as(String alias) {
		return new SchemaMigrations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SchemaMigrations rename(String name) {
		return new SchemaMigrations(name, null);
	}
}
