/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.StreamActionsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamActions extends TableImpl<StreamActionsRecord> {

	private static final long serialVersionUID = -168208;

	/**
	 * The reference instance of <code>mon.stream_actions</code>
	 */
	public static final StreamActions STREAM_ACTIONS = new StreamActions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StreamActionsRecord> getRecordType() {
		return StreamActionsRecord.class;
	}

	/**
	 * The column <code>mon.stream_actions.stream_definition_id</code>.
	 */
	public final TableField<StreamActionsRecord, String> STREAM_DEFINITION_ID = createField("stream_definition_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.stream_actions.action_id</code>.
	 */
	public final TableField<StreamActionsRecord, String> ACTION_ID = createField("action_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.stream_actions.action_type</code>.
	 */
	public final TableField<StreamActionsRecord, String> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>mon.stream_actions</code> table reference
	 */
	public StreamActions() {
		this("stream_actions", null);
	}

	/**
	 * Create an aliased <code>mon.stream_actions</code> table reference
	 */
	public StreamActions(String alias) {
		this(alias, STREAM_ACTIONS);
	}

	private StreamActions(String alias, Table<StreamActionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private StreamActions(String alias, Table<StreamActionsRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StreamActionsRecord> getPrimaryKey() {
		return Keys.KEY_STREAM_ACTIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StreamActionsRecord>> getKeys() {
		return Arrays.<UniqueKey<StreamActionsRecord>>asList(Keys.KEY_STREAM_ACTIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<StreamActionsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<StreamActionsRecord, ?>>asList(Keys.FK_STREAM_ACTION_NOTIFICATION_METHOD_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamActions as(String alias) {
		return new StreamActions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StreamActions rename(String name) {
		return new StreamActions(name, null);
	}
}
