/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.StreamActionsActionTypeRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamActionsActionType extends TableImpl<StreamActionsActionTypeRecord> {

	private static final long serialVersionUID = 1854625394;

	/**
	 * The reference instance of <code>mon.stream_actions_action_type</code>
	 */
	public static final StreamActionsActionType STREAM_ACTIONS_ACTION_TYPE = new StreamActionsActionType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StreamActionsActionTypeRecord> getRecordType() {
		return StreamActionsActionTypeRecord.class;
	}

	/**
	 * The column <code>mon.stream_actions_action_type.name</code>.
	 */
	public final TableField<StreamActionsActionTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>mon.stream_actions_action_type</code> table reference
	 */
	public StreamActionsActionType() {
		this("stream_actions_action_type", null);
	}

	/**
	 * Create an aliased <code>mon.stream_actions_action_type</code> table reference
	 */
	public StreamActionsActionType(String alias) {
		this(alias, STREAM_ACTIONS_ACTION_TYPE);
	}

	private StreamActionsActionType(String alias, Table<StreamActionsActionTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private StreamActionsActionType(String alias, Table<StreamActionsActionTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StreamActionsActionTypeRecord> getPrimaryKey() {
		return Keys.KEY_STREAM_ACTIONS_ACTION_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StreamActionsActionTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<StreamActionsActionTypeRecord>>asList(Keys.KEY_STREAM_ACTIONS_ACTION_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamActionsActionType as(String alias) {
		return new StreamActionsActionType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StreamActionsActionType rename(String name) {
		return new StreamActionsActionType(name, null);
	}
}
