/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.StreamDefinitionRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamDefinition extends TableImpl<StreamDefinitionRecord> {

	private static final long serialVersionUID = -2096406988;

	/**
	 * The reference instance of <code>mon.stream_definition</code>
	 */
	public static final StreamDefinition STREAM_DEFINITION = new StreamDefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StreamDefinitionRecord> getRecordType() {
		return StreamDefinitionRecord.class;
	}

	/**
	 * The column <code>mon.stream_definition.id</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.stream_definition.tenant_id</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.stream_definition.name</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(190).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.stream_definition.description</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mon.stream_definition.select_by</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> SELECT_BY = createField("select_by", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mon.stream_definition.group_by</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> GROUP_BY = createField("group_by", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mon.stream_definition.fire_criteria</code>.
	 */
	public final TableField<StreamDefinitionRecord, String> FIRE_CRITERIA = createField("fire_criteria", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mon.stream_definition.expiration</code>.
	 */
	public final TableField<StreamDefinitionRecord, UInteger> EXPIRATION = createField("expiration", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>mon.stream_definition.actions_enabled</code>.
	 */
	public final TableField<StreamDefinitionRecord, Byte> ACTIONS_ENABLED = createField("actions_enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.stream_definition.created_at</code>.
	 */
	public final TableField<StreamDefinitionRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.stream_definition.updated_at</code>.
	 */
	public final TableField<StreamDefinitionRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.stream_definition.deleted_at</code>.
	 */
	public final TableField<StreamDefinitionRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>mon.stream_definition</code> table reference
	 */
	public StreamDefinition() {
		this("stream_definition", null);
	}

	/**
	 * Create an aliased <code>mon.stream_definition</code> table reference
	 */
	public StreamDefinition(String alias) {
		this(alias, STREAM_DEFINITION);
	}

	private StreamDefinition(String alias, Table<StreamDefinitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private StreamDefinition(String alias, Table<StreamDefinitionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StreamDefinitionRecord> getPrimaryKey() {
		return Keys.KEY_STREAM_DEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StreamDefinitionRecord>> getKeys() {
		return Arrays.<UniqueKey<StreamDefinitionRecord>>asList(Keys.KEY_STREAM_DEFINITION_PRIMARY, Keys.KEY_STREAM_DEFINITION_TENANT_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinition as(String alias) {
		return new StreamDefinition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StreamDefinition rename(String name) {
		return new StreamDefinition(name, null);
	}
}
