/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.SubAlarmDefinitionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubAlarmDefinition extends TableImpl<SubAlarmDefinitionRecord> {

	private static final long serialVersionUID = 799700402;

	/**
	 * The reference instance of <code>mon.sub_alarm_definition</code>
	 */
	public static final SubAlarmDefinition SUB_ALARM_DEFINITION = new SubAlarmDefinition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SubAlarmDefinitionRecord> getRecordType() {
		return SubAlarmDefinitionRecord.class;
	}

	/**
	 * The column <code>mon.sub_alarm_definition.id</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.alarm_definition_id</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, String> ALARM_DEFINITION_ID = createField("alarm_definition_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.function</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, String> FUNCTION = createField("function", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.metric_name</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, String> METRIC_NAME = createField("metric_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.operator</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.threshold</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, Double> THRESHOLD = createField("threshold", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.period</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, Integer> PERIOD = createField("period", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.periods</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, Integer> PERIODS = createField("periods", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.created_at</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition.updated_at</code>.
	 */
	public final TableField<SubAlarmDefinitionRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>mon.sub_alarm_definition</code> table reference
	 */
	public SubAlarmDefinition() {
		this("sub_alarm_definition", null);
	}

	/**
	 * Create an aliased <code>mon.sub_alarm_definition</code> table reference
	 */
	public SubAlarmDefinition(String alias) {
		this(alias, SUB_ALARM_DEFINITION);
	}

	private SubAlarmDefinition(String alias, Table<SubAlarmDefinitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private SubAlarmDefinition(String alias, Table<SubAlarmDefinitionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SubAlarmDefinitionRecord> getPrimaryKey() {
		return Keys.KEY_SUB_ALARM_DEFINITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SubAlarmDefinitionRecord>> getKeys() {
		return Arrays.<UniqueKey<SubAlarmDefinitionRecord>>asList(Keys.KEY_SUB_ALARM_DEFINITION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<SubAlarmDefinitionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<SubAlarmDefinitionRecord, ?>>asList(Keys.FK_SUB_ALARM_DEFINITION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinition as(String alias) {
		return new SubAlarmDefinition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SubAlarmDefinition rename(String name) {
		return new SubAlarmDefinition(name, null);
	}
}
