/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.SubAlarmRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubAlarm extends TableImpl<SubAlarmRecord> {

	private static final long serialVersionUID = 574014792;

	/**
	 * The reference instance of <code>mon.sub_alarm</code>
	 */
	public static final SubAlarm SUB_ALARM = new SubAlarm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SubAlarmRecord> getRecordType() {
		return SubAlarmRecord.class;
	}

	/**
	 * The column <code>mon.sub_alarm.id</code>.
	 */
	public final TableField<SubAlarmRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm.alarm_id</code>.
	 */
	public final TableField<SubAlarmRecord, String> ALARM_ID = createField("alarm_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.sub_alarm.sub_expression_id</code>.
	 */
	public final TableField<SubAlarmRecord, String> SUB_EXPRESSION_ID = createField("sub_expression_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.sub_alarm.expression</code>.
	 */
	public final TableField<SubAlarmRecord, String> EXPRESSION = createField("expression", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm.created_at</code>.
	 */
	public final TableField<SubAlarmRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mon.sub_alarm.updated_at</code>.
	 */
	public final TableField<SubAlarmRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>mon.sub_alarm</code> table reference
	 */
	public SubAlarm() {
		this("sub_alarm", null);
	}

	/**
	 * Create an aliased <code>mon.sub_alarm</code> table reference
	 */
	public SubAlarm(String alias) {
		this(alias, SUB_ALARM);
	}

	private SubAlarm(String alias, Table<SubAlarmRecord> aliased) {
		this(alias, aliased, null);
	}

	private SubAlarm(String alias, Table<SubAlarmRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SubAlarmRecord> getPrimaryKey() {
		return Keys.KEY_SUB_ALARM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SubAlarmRecord>> getKeys() {
		return Arrays.<UniqueKey<SubAlarmRecord>>asList(Keys.KEY_SUB_ALARM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<SubAlarmRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<SubAlarmRecord, ?>>asList(Keys.FK_SUB_ALARM, Keys.FK_SUB_ALARM_EXPR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarm as(String alias) {
		return new SubAlarm(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SubAlarm rename(String name) {
		return new SubAlarm(name, null);
	}
}
