/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.Keys;
import monasca.common.jooq.Mon;
import monasca.common.jooq.tables.records.SubAlarmDefinitionDimensionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubAlarmDefinitionDimension extends TableImpl<SubAlarmDefinitionDimensionRecord> {

	private static final long serialVersionUID = 1614888294;

	/**
	 * The reference instance of <code>mon.sub_alarm_definition_dimension</code>
	 */
	public static final SubAlarmDefinitionDimension SUB_ALARM_DEFINITION_DIMENSION = new SubAlarmDefinitionDimension();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SubAlarmDefinitionDimensionRecord> getRecordType() {
		return SubAlarmDefinitionDimensionRecord.class;
	}

	/**
	 * The column <code>mon.sub_alarm_definition_dimension.sub_alarm_definition_id</code>.
	 */
	public final TableField<SubAlarmDefinitionDimensionRecord, String> SUB_ALARM_DEFINITION_ID = createField("sub_alarm_definition_id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition_dimension.dimension_name</code>.
	 */
	public final TableField<SubAlarmDefinitionDimensionRecord, String> DIMENSION_NAME = createField("dimension_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mon.sub_alarm_definition_dimension.value</code>.
	 */
	public final TableField<SubAlarmDefinitionDimensionRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>mon.sub_alarm_definition_dimension</code> table reference
	 */
	public SubAlarmDefinitionDimension() {
		this("sub_alarm_definition_dimension", null);
	}

	/**
	 * Create an aliased <code>mon.sub_alarm_definition_dimension</code> table reference
	 */
	public SubAlarmDefinitionDimension(String alias) {
		this(alias, SUB_ALARM_DEFINITION_DIMENSION);
	}

	private SubAlarmDefinitionDimension(String alias, Table<SubAlarmDefinitionDimensionRecord> aliased) {
		this(alias, aliased, null);
	}

	private SubAlarmDefinitionDimension(String alias, Table<SubAlarmDefinitionDimensionRecord> aliased, Field<?>[] parameters) {
		super(alias, Mon.MON, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<SubAlarmDefinitionDimensionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<SubAlarmDefinitionDimensionRecord, ?>>asList(Keys.FK_SUB_ALARM_DEFINITION_DIMENSION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionDimension as(String alias) {
		return new SubAlarmDefinitionDimension(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SubAlarmDefinitionDimension rename(String name) {
		return new SubAlarmDefinitionDimension(name, null);
	}
}
