version: 2
updates:
- package-ecosystem: maven
  directories: 
    - "/"
    - "/java"
  schedule:
    interval: weekly
  ignore:
    # ignore Maven APIs/SPIs
    - dependency-name: org.apache.maven:*
  open-pull-requests-limit: 0
