# - pipeline:
#     name: docker-image-build-check
#     manager: independent
#     trigger:
#         my_gerrit:
#             - event: patchset-created
#     success:
#         my_gerrit:
#             verified: 1
#     failure:
#         my_gerrit:
#             verified: -1

- project:
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb:
            voting: false
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - openstack-tox-lower-constraints
        - monasca-base
    gate:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - openstack-tox-lower-constraints

- job:
    name: monasca-base
    timeout: 10200
    post-timeout: 3600
    # pre-run: playbooks/pre.yml
    run: playbooks/run.yml
    # post-run: playbooks/post.yml
    required-projects:
      - openstack/monasca-common
    attempts: 1
    irrelevant-files:
      - ^.*\.rst$
      - ^.*\.md$
      - ^doc/.*$

# - job:
#     name: monasca-base-publish-image
#     parent: monasca-base
#     post-run: playbooks/publish.yml
#     vars:
#         publisher: true
#     secrets:
#         - monasca_dockerhub_creds
