<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.hpcloud</groupId>
  <artifactId>mon-common</artifactId>
  <version>1.0.0</version>
  <url>http://github.com/stackforge/monasca-common</url>
  <packaging>pom</packaging>

  <properties>
    <!-- Versioning -->
    <versionNumber>1.0.0</versionNumber>
    <computedVersion>${versionNumber}-SNAPSHOT</computedVersion>

    <skipITs>true</skipITs>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <build>
    <plugins>
        <plugin>
      <artifactId>maven-antrun-plugin</artifactId>
      <version>1.6</version>
      <executions>
        <execution>
          <phase>clean</phase>
          <configuration>
            <target>
              <echoproperties />
            </target>
          </configuration>
          <goals>
            <goal>run</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.1.1</version>
    <executions>
      <execution>
        <id>package-execution</id>
        <phase>package</phase>
        <goals>
          <goal>exec</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <workingDirectory>java</workingDirectory>
      <!--
      <executable>mvn</executable>
      <arguments>
         <argument>clean</argument>
         <argument>package</argument>
      </arguments>
      -->
      <executable>find</executable>
      <arguments>
         <argument>/usr</argument>
         <argument>-name</argument>
         <argument>mvn</argument>
      </arguments>
    </configuration>
  </plugin>
    </plugins>
  </build>

</project>
