/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.AlarmMetric;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmMetricRecord extends UpdatableRecordImpl<AlarmMetricRecord> implements Record2<String, byte[]> {

	private static final long serialVersionUID = -1831698952;

	/**
	 * Setter for <code>mon.alarm_metric.alarm_id</code>.
	 */
	public void setAlarmId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.alarm_metric.alarm_id</code>.
	 */
	public String getAlarmId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.alarm_metric.metric_definition_dimensions_id</code>.
	 */
	public void setMetricDefinitionDimensionsId(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.alarm_metric.metric_definition_dimensions_id</code>.
	 */
	public byte[] getMetricDefinitionDimensionsId() {
		return (byte[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, byte[]> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, byte[]> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, byte[]> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AlarmMetric.ALARM_METRIC.ALARM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field2() {
		return AlarmMetric.ALARM_METRIC.METRIC_DEFINITION_DIMENSIONS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAlarmId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getMetricDefinitionDimensionsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmMetricRecord value1(String value) {
		setAlarmId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmMetricRecord value2(byte[] value) {
		setMetricDefinitionDimensionsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmMetricRecord values(String value1, byte[] value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlarmMetricRecord
	 */
	public AlarmMetricRecord() {
		super(AlarmMetric.ALARM_METRIC);
	}

	/**
	 * Create a detached, initialised AlarmMetricRecord
	 */
	public AlarmMetricRecord(String alarmId, byte[] metricDefinitionDimensionsId) {
		super(AlarmMetric.ALARM_METRIC);

		setValue(0, alarmId);
		setValue(1, metricDefinitionDimensionsId);
	}
}
