/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.AlarmDefinition;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmDefinitionRecord extends UpdatableRecordImpl<AlarmDefinitionRecord> implements Record11<String, String, String, String, String, String, String, Boolean, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = -1021687864;

	/**
	 * Setter for <code>mon.alarm_definition.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.alarm_definition.tenant_id</code>.
	 */
	public void setTenantId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.tenant_id</code>.
	 */
	public String getTenantId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.alarm_definition.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.alarm_definition.description</code>.
	 */
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.alarm_definition.expression</code>.
	 */
	public void setExpression(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.expression</code>.
	 */
	public String getExpression() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mon.alarm_definition.severity</code>.
	 */
	public void setSeverity(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.severity</code>.
	 */
	public String getSeverity() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mon.alarm_definition.match_by</code>.
	 */
	public void setMatchBy(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.match_by</code>.
	 */
	public String getMatchBy() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mon.alarm_definition.actions_enabled</code>.
	 */
	public void setActionsEnabled(Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.actions_enabled</code>.
	 */
	public Boolean getActionsEnabled() {
		return (Boolean) getValue(7);
	}

	/**
	 * Setter for <code>mon.alarm_definition.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>mon.alarm_definition.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>mon.alarm_definition.deleted_at</code>.
	 */
	public void setDeletedAt(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mon.alarm_definition.deleted_at</code>.
	 */
	public Timestamp getDeletedAt() {
		return (Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, String, String, String, Boolean, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, String, String, String, Boolean, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AlarmDefinition.ALARM_DEFINITION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AlarmDefinition.ALARM_DEFINITION.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AlarmDefinition.ALARM_DEFINITION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AlarmDefinition.ALARM_DEFINITION.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return AlarmDefinition.ALARM_DEFINITION.EXPRESSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return AlarmDefinition.ALARM_DEFINITION.SEVERITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return AlarmDefinition.ALARM_DEFINITION.MATCH_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field8() {
		return AlarmDefinition.ALARM_DEFINITION.ACTIONS_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return AlarmDefinition.ALARM_DEFINITION.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return AlarmDefinition.ALARM_DEFINITION.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return AlarmDefinition.ALARM_DEFINITION.DELETED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getExpression();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getSeverity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getMatchBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value8() {
		return getActionsEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getDeletedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value2(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value5(String value) {
		setExpression(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value6(String value) {
		setSeverity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value7(String value) {
		setMatchBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value8(Boolean value) {
		setActionsEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value9(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value10(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord value11(Timestamp value) {
		setDeletedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmDefinitionRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Boolean value8, Timestamp value9, Timestamp value10, Timestamp value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlarmDefinitionRecord
	 */
	public AlarmDefinitionRecord() {
		super(AlarmDefinition.ALARM_DEFINITION);
	}

	/**
	 * Create a detached, initialised AlarmDefinitionRecord
	 */
	public AlarmDefinitionRecord(String id, String tenantId, String name, String description, String expression, String severity, String matchBy, Boolean actionsEnabled, Timestamp createdAt, Timestamp updatedAt, Timestamp deletedAt) {
		super(AlarmDefinition.ALARM_DEFINITION);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, name);
		setValue(3, description);
		setValue(4, expression);
		setValue(5, severity);
		setValue(6, matchBy);
		setValue(7, actionsEnabled);
		setValue(8, createdAt);
		setValue(9, updatedAt);
		setValue(10, deletedAt);
	}
}
