/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.AlarmAction;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmActionRecord extends UpdatableRecordImpl<AlarmActionRecord> implements Record3<String, String, String> {

	private static final long serialVersionUID = -2059761414;

	/**
	 * Setter for <code>mon.alarm_action.alarm_definition_id</code>.
	 */
	public void setAlarmDefinitionId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.alarm_action.alarm_definition_id</code>.
	 */
	public String getAlarmDefinitionId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.alarm_action.alarm_state</code>.
	 */
	public void setAlarmState(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.alarm_action.alarm_state</code>.
	 */
	public String getAlarmState() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.alarm_action.action_id</code>.
	 */
	public void setActionId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.alarm_action.action_id</code>.
	 */
	public String getActionId() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AlarmAction.ALARM_ACTION.ALARM_DEFINITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AlarmAction.ALARM_ACTION.ALARM_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AlarmAction.ALARM_ACTION.ACTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAlarmDefinitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAlarmState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getActionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmActionRecord value1(String value) {
		setAlarmDefinitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmActionRecord value2(String value) {
		setAlarmState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmActionRecord value3(String value) {
		setActionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmActionRecord values(String value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlarmActionRecord
	 */
	public AlarmActionRecord() {
		super(AlarmAction.ALARM_ACTION);
	}

	/**
	 * Create a detached, initialised AlarmActionRecord
	 */
	public AlarmActionRecord(String alarmDefinitionId, String alarmState, String actionId) {
		super(AlarmAction.ALARM_ACTION);

		setValue(0, alarmDefinitionId);
		setValue(1, alarmState);
		setValue(2, actionId);
	}
}
