/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.Alarm;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmRecord extends UpdatableRecordImpl<AlarmRecord> implements Record8<String, String, String, String, String, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = 271434040;

	/**
	 * Setter for <code>mon.alarm.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.alarm.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.alarm.alarm_definition_id</code>.
	 */
	public void setAlarmDefinitionId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.alarm.alarm_definition_id</code>.
	 */
	public String getAlarmDefinitionId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.alarm.state</code>.
	 */
	public void setState(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.alarm.state</code>.
	 */
	public String getState() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.alarm.lifecycle_state</code>.
	 */
	public void setLifecycleState(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.alarm.lifecycle_state</code>.
	 */
	public String getLifecycleState() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.alarm.link</code>.
	 */
	public void setLink(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.alarm.link</code>.
	 */
	public String getLink() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mon.alarm.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.alarm.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>mon.alarm.state_updated_at</code>.
	 */
	public void setStateUpdatedAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mon.alarm.state_updated_at</code>.
	 */
	public Timestamp getStateUpdatedAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>mon.alarm.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mon.alarm.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Alarm.ALARM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Alarm.ALARM.ALARM_DEFINITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Alarm.ALARM.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Alarm.ALARM.LIFECYCLE_STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Alarm.ALARM.LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Alarm.ALARM.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Alarm.ALARM.STATE_UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return Alarm.ALARM.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAlarmDefinitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getLifecycleState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getStateUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value2(String value) {
		setAlarmDefinitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value3(String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value4(String value) {
		setLifecycleState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value5(String value) {
		setLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value6(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value7(Timestamp value) {
		setStateUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord value8(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlarmRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlarmRecord
	 */
	public AlarmRecord() {
		super(Alarm.ALARM);
	}

	/**
	 * Create a detached, initialised AlarmRecord
	 */
	public AlarmRecord(String id, String alarmDefinitionId, String state, String lifecycleState, String link, Timestamp createdAt, Timestamp stateUpdatedAt, Timestamp updatedAt) {
		super(Alarm.ALARM);

		setValue(0, id);
		setValue(1, alarmDefinitionId);
		setValue(2, state);
		setValue(3, lifecycleState);
		setValue(4, link);
		setValue(5, createdAt);
		setValue(6, stateUpdatedAt);
		setValue(7, updatedAt);
	}
}
