/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.EventTransform;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventTransformRecord extends UpdatableRecordImpl<EventTransformRecord> implements Record9<String, String, String, String, String, Byte, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = -1185675839;

	/**
	 * Setter for <code>mon.event_transform.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.event_transform.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.event_transform.tenant_id</code>.
	 */
	public void setTenantId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.event_transform.tenant_id</code>.
	 */
	public String getTenantId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.event_transform.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.event_transform.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.event_transform.description</code>.
	 */
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.event_transform.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.event_transform.specification</code>.
	 */
	public void setSpecification(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.event_transform.specification</code>.
	 */
	public String getSpecification() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mon.event_transform.enabled</code>.
	 */
	public void setEnabled(Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.event_transform.enabled</code>.
	 */
	public Byte getEnabled() {
		return (Byte) getValue(5);
	}

	/**
	 * Setter for <code>mon.event_transform.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mon.event_transform.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>mon.event_transform.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mon.event_transform.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>mon.event_transform.deleted_at</code>.
	 */
	public void setDeletedAt(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mon.event_transform.deleted_at</code>.
	 */
	public Timestamp getDeletedAt() {
		return (Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return EventTransform.EVENT_TRANSFORM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return EventTransform.EVENT_TRANSFORM.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return EventTransform.EVENT_TRANSFORM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return EventTransform.EVENT_TRANSFORM.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EventTransform.EVENT_TRANSFORM.SPECIFICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field6() {
		return EventTransform.EVENT_TRANSFORM.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return EventTransform.EVENT_TRANSFORM.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return EventTransform.EVENT_TRANSFORM.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return EventTransform.EVENT_TRANSFORM.DELETED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSpecification();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value6() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getDeletedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value2(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value5(String value) {
		setSpecification(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value6(Byte value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value7(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value8(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord value9(Timestamp value) {
		setDeletedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventTransformRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, Timestamp value7, Timestamp value8, Timestamp value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventTransformRecord
	 */
	public EventTransformRecord() {
		super(EventTransform.EVENT_TRANSFORM);
	}

	/**
	 * Create a detached, initialised EventTransformRecord
	 */
	public EventTransformRecord(String id, String tenantId, String name, String description, String specification, Byte enabled, Timestamp createdAt, Timestamp updatedAt, Timestamp deletedAt) {
		super(EventTransform.EVENT_TRANSFORM);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, name);
		setValue(3, description);
		setValue(4, specification);
		setValue(5, enabled);
		setValue(6, createdAt);
		setValue(7, updatedAt);
		setValue(8, deletedAt);
	}
}
