/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.MetricDefinitionDimensions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricDefinitionDimensionsRecord extends UpdatableRecordImpl<MetricDefinitionDimensionsRecord> implements Record3<byte[], byte[], byte[]> {

	private static final long serialVersionUID = -1975958668;

	/**
	 * Setter for <code>mon.metric_definition_dimensions.id</code>.
	 */
	public void setId(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.metric_definition_dimensions.id</code>.
	 */
	public byte[] getId() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>mon.metric_definition_dimensions.metric_definition_id</code>.
	 */
	public void setMetricDefinitionId(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.metric_definition_dimensions.metric_definition_id</code>.
	 */
	public byte[] getMetricDefinitionId() {
		return (byte[]) getValue(1);
	}

	/**
	 * Setter for <code>mon.metric_definition_dimensions.metric_dimension_set_id</code>.
	 */
	public void setMetricDimensionSetId(byte[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.metric_definition_dimensions.metric_dimension_set_id</code>.
	 */
	public byte[] getMetricDimensionSetId() {
		return (byte[]) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<byte[]> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<byte[], byte[], byte[]> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<byte[], byte[], byte[]> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field1() {
		return MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field2() {
		return MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS.METRIC_DEFINITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field3() {
		return MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS.METRIC_DIMENSION_SET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getMetricDefinitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getMetricDimensionSetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionDimensionsRecord value1(byte[] value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionDimensionsRecord value2(byte[] value) {
		setMetricDefinitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionDimensionsRecord value3(byte[] value) {
		setMetricDimensionSetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionDimensionsRecord values(byte[] value1, byte[] value2, byte[] value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MetricDefinitionDimensionsRecord
	 */
	public MetricDefinitionDimensionsRecord() {
		super(MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS);
	}

	/**
	 * Create a detached, initialised MetricDefinitionDimensionsRecord
	 */
	public MetricDefinitionDimensionsRecord(byte[] id, byte[] metricDefinitionId, byte[] metricDimensionSetId) {
		super(MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS);

		setValue(0, id);
		setValue(1, metricDefinitionId);
		setValue(2, metricDimensionSetId);
	}
}
