/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.MetricDefinition;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricDefinitionRecord extends UpdatableRecordImpl<MetricDefinitionRecord> implements Record4<byte[], String, String, String> {

	private static final long serialVersionUID = -666218610;

	/**
	 * Setter for <code>mon.metric_definition.id</code>.
	 */
	public void setId(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.metric_definition.id</code>.
	 */
	public byte[] getId() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>mon.metric_definition.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.metric_definition.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.metric_definition.tenant_id</code>.
	 */
	public void setTenantId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.metric_definition.tenant_id</code>.
	 */
	public String getTenantId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.metric_definition.region</code>.
	 */
	public void setRegion(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.metric_definition.region</code>.
	 */
	public String getRegion() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<byte[]> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<byte[], String, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<byte[], String, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field1() {
		return MetricDefinition.METRIC_DEFINITION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return MetricDefinition.METRIC_DEFINITION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return MetricDefinition.METRIC_DEFINITION.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return MetricDefinition.METRIC_DEFINITION.REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getRegion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionRecord value1(byte[] value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionRecord value3(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionRecord value4(String value) {
		setRegion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDefinitionRecord values(byte[] value1, String value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MetricDefinitionRecord
	 */
	public MetricDefinitionRecord() {
		super(MetricDefinition.METRIC_DEFINITION);
	}

	/**
	 * Create a detached, initialised MetricDefinitionRecord
	 */
	public MetricDefinitionRecord(byte[] id, String name, String tenantId, String region) {
		super(MetricDefinition.METRIC_DEFINITION);

		setValue(0, id);
		setValue(1, name);
		setValue(2, tenantId);
		setValue(3, region);
	}
}
