/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.MetricDimension;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * PRIMARY KEY (`id`)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricDimensionRecord extends TableRecordImpl<MetricDimensionRecord> implements Record3<byte[], String, String> {

	private static final long serialVersionUID = 1604946489;

	/**
	 * Setter for <code>mon.metric_dimension.dimension_set_id</code>.
	 */
	public void setDimensionSetId(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.metric_dimension.dimension_set_id</code>.
	 */
	public byte[] getDimensionSetId() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>mon.metric_dimension.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.metric_dimension.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.metric_dimension.value</code>.
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.metric_dimension.value</code>.
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<byte[], String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<byte[], String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field1() {
		return MetricDimension.METRIC_DIMENSION.DIMENSION_SET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return MetricDimension.METRIC_DIMENSION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return MetricDimension.METRIC_DIMENSION.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getDimensionSetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDimensionRecord value1(byte[] value) {
		setDimensionSetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDimensionRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDimensionRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MetricDimensionRecord values(byte[] value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MetricDimensionRecord
	 */
	public MetricDimensionRecord() {
		super(MetricDimension.METRIC_DIMENSION);
	}

	/**
	 * Create a detached, initialised MetricDimensionRecord
	 */
	public MetricDimensionRecord(byte[] dimensionSetId, String name, String value) {
		super(MetricDimension.METRIC_DIMENSION);

		setValue(0, dimensionSetId);
		setValue(1, name);
		setValue(2, value);
	}
}
