/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.NotificationMethod;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationMethodRecord extends UpdatableRecordImpl<NotificationMethodRecord> implements Record7<String, String, String, String, String, Timestamp, Timestamp> {

	private static final long serialVersionUID = -1441818251;

	/**
	 * Setter for <code>mon.notification_method.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.notification_method.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.notification_method.tenant_id</code>.
	 */
	public void setTenantId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.notification_method.tenant_id</code>.
	 */
	public String getTenantId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.notification_method.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.notification_method.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.notification_method.type</code>.
	 */
	public void setType(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.notification_method.type</code>.
	 */
	public String getType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.notification_method.address</code>.
	 */
	public void setAddress(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.notification_method.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mon.notification_method.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.notification_method.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>mon.notification_method.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mon.notification_method.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return NotificationMethod.NOTIFICATION_METHOD.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return NotificationMethod.NOTIFICATION_METHOD.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return NotificationMethod.NOTIFICATION_METHOD.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return NotificationMethod.NOTIFICATION_METHOD.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return NotificationMethod.NOTIFICATION_METHOD.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return NotificationMethod.NOTIFICATION_METHOD.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return NotificationMethod.NOTIFICATION_METHOD.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value2(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value4(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value5(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value6(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord value7(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotificationMethodRecord
	 */
	public NotificationMethodRecord() {
		super(NotificationMethod.NOTIFICATION_METHOD);
	}

	/**
	 * Create a detached, initialised NotificationMethodRecord
	 */
	public NotificationMethodRecord(String id, String tenantId, String name, String type, String address, Timestamp createdAt, Timestamp updatedAt) {
		super(NotificationMethod.NOTIFICATION_METHOD);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, name);
		setValue(3, type);
		setValue(4, address);
		setValue(5, createdAt);
		setValue(6, updatedAt);
	}
}
