/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.NotificationMethodType;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationMethodTypeRecord extends UpdatableRecordImpl<NotificationMethodTypeRecord> implements Record1<String> {

	private static final long serialVersionUID = 1367204716;

	/**
	 * Setter for <code>mon.notification_method_type.name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.notification_method_type.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<String> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<String> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return NotificationMethodType.NOTIFICATION_METHOD_TYPE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodTypeRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationMethodTypeRecord values(String value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotificationMethodTypeRecord
	 */
	public NotificationMethodTypeRecord() {
		super(NotificationMethodType.NOTIFICATION_METHOD_TYPE);
	}

	/**
	 * Create a detached, initialised NotificationMethodTypeRecord
	 */
	public NotificationMethodTypeRecord(String name) {
		super(NotificationMethodType.NOTIFICATION_METHOD_TYPE);

		setValue(0, name);
	}
}
