/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.StreamDefinition;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamDefinitionRecord extends UpdatableRecordImpl<StreamDefinitionRecord> implements Record12<String, String, String, String, String, String, String, UInteger, Byte, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = 1749849548;

	/**
	 * Setter for <code>mon.stream_definition.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.stream_definition.tenant_id</code>.
	 */
	public void setTenantId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.tenant_id</code>.
	 */
	public String getTenantId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.stream_definition.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.stream_definition.description</code>.
	 */
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.stream_definition.select_by</code>.
	 */
	public void setSelectBy(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.select_by</code>.
	 */
	public String getSelectBy() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mon.stream_definition.group_by</code>.
	 */
	public void setGroupBy(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.group_by</code>.
	 */
	public String getGroupBy() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mon.stream_definition.fire_criteria</code>.
	 */
	public void setFireCriteria(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.fire_criteria</code>.
	 */
	public String getFireCriteria() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mon.stream_definition.expiration</code>.
	 */
	public void setExpiration(UInteger value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.expiration</code>.
	 */
	public UInteger getExpiration() {
		return (UInteger) getValue(7);
	}

	/**
	 * Setter for <code>mon.stream_definition.actions_enabled</code>.
	 */
	public void setActionsEnabled(Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.actions_enabled</code>.
	 */
	public Byte getActionsEnabled() {
		return (Byte) getValue(8);
	}

	/**
	 * Setter for <code>mon.stream_definition.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>mon.stream_definition.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>mon.stream_definition.deleted_at</code>.
	 */
	public void setDeletedAt(Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>mon.stream_definition.deleted_at</code>.
	 */
	public Timestamp getDeletedAt() {
		return (Timestamp) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<String, String, String, String, String, String, String, UInteger, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<String, String, String, String, String, String, String, UInteger, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return StreamDefinition.STREAM_DEFINITION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return StreamDefinition.STREAM_DEFINITION.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return StreamDefinition.STREAM_DEFINITION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return StreamDefinition.STREAM_DEFINITION.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return StreamDefinition.STREAM_DEFINITION.SELECT_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return StreamDefinition.STREAM_DEFINITION.GROUP_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return StreamDefinition.STREAM_DEFINITION.FIRE_CRITERIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field8() {
		return StreamDefinition.STREAM_DEFINITION.EXPIRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field9() {
		return StreamDefinition.STREAM_DEFINITION.ACTIONS_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return StreamDefinition.STREAM_DEFINITION.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return StreamDefinition.STREAM_DEFINITION.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field12() {
		return StreamDefinition.STREAM_DEFINITION.DELETED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSelectBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getGroupBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getFireCriteria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value8() {
		return getExpiration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value9() {
		return getActionsEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value12() {
		return getDeletedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value2(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value5(String value) {
		setSelectBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value6(String value) {
		setGroupBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value7(String value) {
		setFireCriteria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value8(UInteger value) {
		setExpiration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value9(Byte value) {
		setActionsEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value10(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value11(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord value12(Timestamp value) {
		setDeletedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamDefinitionRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, UInteger value8, Byte value9, Timestamp value10, Timestamp value11, Timestamp value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StreamDefinitionRecord
	 */
	public StreamDefinitionRecord() {
		super(StreamDefinition.STREAM_DEFINITION);
	}

	/**
	 * Create a detached, initialised StreamDefinitionRecord
	 */
	public StreamDefinitionRecord(String id, String tenantId, String name, String description, String selectBy, String groupBy, String fireCriteria, UInteger expiration, Byte actionsEnabled, Timestamp createdAt, Timestamp updatedAt, Timestamp deletedAt) {
		super(StreamDefinition.STREAM_DEFINITION);

		setValue(0, id);
		setValue(1, tenantId);
		setValue(2, name);
		setValue(3, description);
		setValue(4, selectBy);
		setValue(5, groupBy);
		setValue(6, fireCriteria);
		setValue(7, expiration);
		setValue(8, actionsEnabled);
		setValue(9, createdAt);
		setValue(10, updatedAt);
		setValue(11, deletedAt);
	}
}
