/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.StreamActions;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StreamActionsRecord extends UpdatableRecordImpl<StreamActionsRecord> implements Record3<String, String, String> {

	private static final long serialVersionUID = 1107063665;

	/**
	 * Setter for <code>mon.stream_actions.stream_definition_id</code>.
	 */
	public void setStreamDefinitionId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.stream_actions.stream_definition_id</code>.
	 */
	public String getStreamDefinitionId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.stream_actions.action_id</code>.
	 */
	public void setActionId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.stream_actions.action_id</code>.
	 */
	public String getActionId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.stream_actions.action_type</code>.
	 */
	public void setActionType(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.stream_actions.action_type</code>.
	 */
	public String getActionType() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return StreamActions.STREAM_ACTIONS.STREAM_DEFINITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return StreamActions.STREAM_ACTIONS.ACTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return StreamActions.STREAM_ACTIONS.ACTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getStreamDefinitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getActionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getActionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamActionsRecord value1(String value) {
		setStreamDefinitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamActionsRecord value2(String value) {
		setActionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamActionsRecord value3(String value) {
		setActionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StreamActionsRecord values(String value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StreamActionsRecord
	 */
	public StreamActionsRecord() {
		super(StreamActions.STREAM_ACTIONS);
	}

	/**
	 * Create a detached, initialised StreamActionsRecord
	 */
	public StreamActionsRecord(String streamDefinitionId, String actionId, String actionType) {
		super(StreamActions.STREAM_ACTIONS);

		setValue(0, streamDefinitionId);
		setValue(1, actionId);
		setValue(2, actionType);
	}
}
