/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.SubAlarmDefinition;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubAlarmDefinitionRecord extends UpdatableRecordImpl<SubAlarmDefinitionRecord> implements Record10<String, String, String, String, String, Double, Integer, Integer, Timestamp, Timestamp> {

	private static final long serialVersionUID = 1281767084;

	/**
	 * Setter for <code>mon.sub_alarm_definition.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.alarm_definition_id</code>.
	 */
	public void setAlarmDefinitionId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.alarm_definition_id</code>.
	 */
	public String getAlarmDefinitionId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.function</code>.
	 */
	public void setFunction(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.function</code>.
	 */
	public String getFunction() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.metric_name</code>.
	 */
	public void setMetricName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.metric_name</code>.
	 */
	public String getMetricName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.operator</code>.
	 */
	public void setOperator(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.operator</code>.
	 */
	public String getOperator() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.threshold</code>.
	 */
	public void setThreshold(Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.threshold</code>.
	 */
	public Double getThreshold() {
		return (Double) getValue(5);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.period</code>.
	 */
	public void setPeriod(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.period</code>.
	 */
	public Integer getPeriod() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.periods</code>.
	 */
	public void setPeriods(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.periods</code>.
	 */
	public Integer getPeriods() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, String, String, String, String, Double, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, String, String, String, String, Double, Integer, Integer, Timestamp, Timestamp> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.ALARM_DEFINITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.FUNCTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.METRIC_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.OPERATOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field6() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.THRESHOLD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.PERIODS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return SubAlarmDefinition.SUB_ALARM_DEFINITION.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAlarmDefinitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFunction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMetricName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getOperator();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value6() {
		return getThreshold();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getPeriods();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value2(String value) {
		setAlarmDefinitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value3(String value) {
		setFunction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value4(String value) {
		setMetricName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value5(String value) {
		setOperator(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value6(Double value) {
		setThreshold(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value7(Integer value) {
		setPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value8(Integer value) {
		setPeriods(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value9(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord value10(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionRecord values(String value1, String value2, String value3, String value4, String value5, Double value6, Integer value7, Integer value8, Timestamp value9, Timestamp value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubAlarmDefinitionRecord
	 */
	public SubAlarmDefinitionRecord() {
		super(SubAlarmDefinition.SUB_ALARM_DEFINITION);
	}

	/**
	 * Create a detached, initialised SubAlarmDefinitionRecord
	 */
	public SubAlarmDefinitionRecord(String id, String alarmDefinitionId, String function, String metricName, String operator, Double threshold, Integer period, Integer periods, Timestamp createdAt, Timestamp updatedAt) {
		super(SubAlarmDefinition.SUB_ALARM_DEFINITION);

		setValue(0, id);
		setValue(1, alarmDefinitionId);
		setValue(2, function);
		setValue(3, metricName);
		setValue(4, operator);
		setValue(5, threshold);
		setValue(6, period);
		setValue(7, periods);
		setValue(8, createdAt);
		setValue(9, updatedAt);
	}
}
