/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import monasca.common.jooq.tables.SubAlarm;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubAlarmRecord extends UpdatableRecordImpl<SubAlarmRecord> implements Record6<String, String, String, String, Timestamp, Timestamp> {

	private static final long serialVersionUID = -1013701471;

	/**
	 * Setter for <code>mon.sub_alarm.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.sub_alarm.alarm_id</code>.
	 */
	public void setAlarmId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm.alarm_id</code>.
	 */
	public String getAlarmId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.sub_alarm.sub_expression_id</code>.
	 */
	public void setSubExpressionId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm.sub_expression_id</code>.
	 */
	public String getSubExpressionId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mon.sub_alarm.expression</code>.
	 */
	public void setExpression(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm.expression</code>.
	 */
	public String getExpression() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mon.sub_alarm.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>mon.sub_alarm.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, String, Timestamp, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, String, Timestamp, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SubAlarm.SUB_ALARM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SubAlarm.SUB_ALARM.ALARM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SubAlarm.SUB_ALARM.SUB_EXPRESSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SubAlarm.SUB_ALARM.EXPRESSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return SubAlarm.SUB_ALARM.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return SubAlarm.SUB_ALARM.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAlarmId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSubExpressionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getExpression();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord value2(String value) {
		setAlarmId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord value3(String value) {
		setSubExpressionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord value4(String value) {
		setExpression(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord value5(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord value6(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmRecord values(String value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubAlarmRecord
	 */
	public SubAlarmRecord() {
		super(SubAlarm.SUB_ALARM);
	}

	/**
	 * Create a detached, initialised SubAlarmRecord
	 */
	public SubAlarmRecord(String id, String alarmId, String subExpressionId, String expression, Timestamp createdAt, Timestamp updatedAt) {
		super(SubAlarm.SUB_ALARM);

		setValue(0, id);
		setValue(1, alarmId);
		setValue(2, subExpressionId);
		setValue(3, expression);
		setValue(4, createdAt);
		setValue(5, updatedAt);
	}
}
