/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq.tables.records;


import javax.annotation.Generated;

import monasca.common.jooq.tables.SubAlarmDefinitionDimension;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubAlarmDefinitionDimensionRecord extends TableRecordImpl<SubAlarmDefinitionDimensionRecord> implements Record3<String, String, String> {

	private static final long serialVersionUID = -107626368;

	/**
	 * Setter for <code>mon.sub_alarm_definition_dimension.sub_alarm_definition_id</code>.
	 */
	public void setSubAlarmDefinitionId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition_dimension.sub_alarm_definition_id</code>.
	 */
	public String getSubAlarmDefinitionId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition_dimension.dimension_name</code>.
	 */
	public void setDimensionName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition_dimension.dimension_name</code>.
	 */
	public String getDimensionName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mon.sub_alarm_definition_dimension.value</code>.
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mon.sub_alarm_definition_dimension.value</code>.
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION.SUB_ALARM_DEFINITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION.DIMENSION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSubAlarmDefinitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDimensionName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionDimensionRecord value1(String value) {
		setSubAlarmDefinitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionDimensionRecord value2(String value) {
		setDimensionName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionDimensionRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SubAlarmDefinitionDimensionRecord values(String value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SubAlarmDefinitionDimensionRecord
	 */
	public SubAlarmDefinitionDimensionRecord() {
		super(SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION);
	}

	/**
	 * Create a detached, initialised SubAlarmDefinitionDimensionRecord
	 */
	public SubAlarmDefinitionDimensionRecord(String subAlarmDefinitionId, String dimensionName, String value) {
		super(SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION);

		setValue(0, subAlarmDefinitionId);
		setValue(1, dimensionName);
		setValue(2, value);
	}
}
