/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq;


import javax.annotation.Generated;

import monasca.common.jooq.tables.Alarm;
import monasca.common.jooq.tables.AlarmAction;
import monasca.common.jooq.tables.AlarmDefinition;
import monasca.common.jooq.tables.AlarmDefinitionSeverity;
import monasca.common.jooq.tables.AlarmMetric;
import monasca.common.jooq.tables.AlarmState;
import monasca.common.jooq.tables.EventTransform;
import monasca.common.jooq.tables.MetricDefinition;
import monasca.common.jooq.tables.MetricDefinitionDimensions;
import monasca.common.jooq.tables.MetricDimension;
import monasca.common.jooq.tables.NotificationMethod;
import monasca.common.jooq.tables.NotificationMethodType;
import monasca.common.jooq.tables.SchemaMigrations;
import monasca.common.jooq.tables.StreamActions;
import monasca.common.jooq.tables.StreamActionsActionType;
import monasca.common.jooq.tables.StreamDefinition;
import monasca.common.jooq.tables.SubAlarm;
import monasca.common.jooq.tables.SubAlarmDefinition;
import monasca.common.jooq.tables.SubAlarmDefinitionDimension;
import monasca.common.jooq.tables.records.AlarmActionRecord;
import monasca.common.jooq.tables.records.AlarmDefinitionRecord;
import monasca.common.jooq.tables.records.AlarmDefinitionSeverityRecord;
import monasca.common.jooq.tables.records.AlarmMetricRecord;
import monasca.common.jooq.tables.records.AlarmRecord;
import monasca.common.jooq.tables.records.AlarmStateRecord;
import monasca.common.jooq.tables.records.EventTransformRecord;
import monasca.common.jooq.tables.records.MetricDefinitionDimensionsRecord;
import monasca.common.jooq.tables.records.MetricDefinitionRecord;
import monasca.common.jooq.tables.records.MetricDimensionRecord;
import monasca.common.jooq.tables.records.NotificationMethodRecord;
import monasca.common.jooq.tables.records.NotificationMethodTypeRecord;
import monasca.common.jooq.tables.records.SchemaMigrationsRecord;
import monasca.common.jooq.tables.records.StreamActionsActionTypeRecord;
import monasca.common.jooq.tables.records.StreamActionsRecord;
import monasca.common.jooq.tables.records.StreamDefinitionRecord;
import monasca.common.jooq.tables.records.SubAlarmDefinitionDimensionRecord;
import monasca.common.jooq.tables.records.SubAlarmDefinitionRecord;
import monasca.common.jooq.tables.records.SubAlarmRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>mon</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AlarmRecord> KEY_ALARM_PRIMARY = UniqueKeys0.KEY_ALARM_PRIMARY;
	public static final UniqueKey<AlarmActionRecord> KEY_ALARM_ACTION_PRIMARY = UniqueKeys0.KEY_ALARM_ACTION_PRIMARY;
	public static final UniqueKey<AlarmDefinitionRecord> KEY_ALARM_DEFINITION_PRIMARY = UniqueKeys0.KEY_ALARM_DEFINITION_PRIMARY;
	public static final UniqueKey<AlarmDefinitionSeverityRecord> KEY_ALARM_DEFINITION_SEVERITY_PRIMARY = UniqueKeys0.KEY_ALARM_DEFINITION_SEVERITY_PRIMARY;
	public static final UniqueKey<AlarmMetricRecord> KEY_ALARM_METRIC_PRIMARY = UniqueKeys0.KEY_ALARM_METRIC_PRIMARY;
	public static final UniqueKey<AlarmStateRecord> KEY_ALARM_STATE_PRIMARY = UniqueKeys0.KEY_ALARM_STATE_PRIMARY;
	public static final UniqueKey<EventTransformRecord> KEY_EVENT_TRANSFORM_PRIMARY = UniqueKeys0.KEY_EVENT_TRANSFORM_PRIMARY;
	public static final UniqueKey<EventTransformRecord> KEY_EVENT_TRANSFORM_TENANT_NAME = UniqueKeys0.KEY_EVENT_TRANSFORM_TENANT_NAME;
	public static final UniqueKey<MetricDefinitionRecord> KEY_METRIC_DEFINITION_PRIMARY = UniqueKeys0.KEY_METRIC_DEFINITION_PRIMARY;
	public static final UniqueKey<MetricDefinitionDimensionsRecord> KEY_METRIC_DEFINITION_DIMENSIONS_PRIMARY = UniqueKeys0.KEY_METRIC_DEFINITION_DIMENSIONS_PRIMARY;
	public static final UniqueKey<MetricDimensionRecord> KEY_METRIC_DIMENSION_METRIC_DIMENSION_KEY = UniqueKeys0.KEY_METRIC_DIMENSION_METRIC_DIMENSION_KEY;
	public static final UniqueKey<NotificationMethodRecord> KEY_NOTIFICATION_METHOD_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_METHOD_PRIMARY;
	public static final UniqueKey<NotificationMethodTypeRecord> KEY_NOTIFICATION_METHOD_TYPE_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_METHOD_TYPE_PRIMARY;
	public static final UniqueKey<SchemaMigrationsRecord> KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS = UniqueKeys0.KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS;
	public static final UniqueKey<StreamActionsRecord> KEY_STREAM_ACTIONS_PRIMARY = UniqueKeys0.KEY_STREAM_ACTIONS_PRIMARY;
	public static final UniqueKey<StreamActionsActionTypeRecord> KEY_STREAM_ACTIONS_ACTION_TYPE_PRIMARY = UniqueKeys0.KEY_STREAM_ACTIONS_ACTION_TYPE_PRIMARY;
	public static final UniqueKey<StreamDefinitionRecord> KEY_STREAM_DEFINITION_PRIMARY = UniqueKeys0.KEY_STREAM_DEFINITION_PRIMARY;
	public static final UniqueKey<StreamDefinitionRecord> KEY_STREAM_DEFINITION_TENANT_NAME = UniqueKeys0.KEY_STREAM_DEFINITION_TENANT_NAME;
	public static final UniqueKey<SubAlarmRecord> KEY_SUB_ALARM_PRIMARY = UniqueKeys0.KEY_SUB_ALARM_PRIMARY;
	public static final UniqueKey<SubAlarmDefinitionRecord> KEY_SUB_ALARM_DEFINITION_PRIMARY = UniqueKeys0.KEY_SUB_ALARM_DEFINITION_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AlarmActionRecord, NotificationMethodRecord> FK_ALARM_ACTION_NOTIFICATION_METHOD_ID = ForeignKeys0.FK_ALARM_ACTION_NOTIFICATION_METHOD_ID;
	public static final ForeignKey<AlarmMetricRecord, AlarmRecord> FK_ALARM_ID = ForeignKeys0.FK_ALARM_ID;
	public static final ForeignKey<StreamActionsRecord, NotificationMethodRecord> FK_STREAM_ACTION_NOTIFICATION_METHOD_ID = ForeignKeys0.FK_STREAM_ACTION_NOTIFICATION_METHOD_ID;
	public static final ForeignKey<SubAlarmRecord, AlarmRecord> FK_SUB_ALARM = ForeignKeys0.FK_SUB_ALARM;
	public static final ForeignKey<SubAlarmRecord, SubAlarmDefinitionRecord> FK_SUB_ALARM_EXPR = ForeignKeys0.FK_SUB_ALARM_EXPR;
	public static final ForeignKey<SubAlarmDefinitionRecord, AlarmDefinitionRecord> FK_SUB_ALARM_DEFINITION = ForeignKeys0.FK_SUB_ALARM_DEFINITION;
	public static final ForeignKey<SubAlarmDefinitionDimensionRecord, SubAlarmDefinitionRecord> FK_SUB_ALARM_DEFINITION_DIMENSION = ForeignKeys0.FK_SUB_ALARM_DEFINITION_DIMENSION;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AlarmRecord> KEY_ALARM_PRIMARY = createUniqueKey(Alarm.ALARM, Alarm.ALARM.ID);
		public static final UniqueKey<AlarmActionRecord> KEY_ALARM_ACTION_PRIMARY = createUniqueKey(AlarmAction.ALARM_ACTION, AlarmAction.ALARM_ACTION.ALARM_DEFINITION_ID, AlarmAction.ALARM_ACTION.ALARM_STATE, AlarmAction.ALARM_ACTION.ACTION_ID);
		public static final UniqueKey<AlarmDefinitionRecord> KEY_ALARM_DEFINITION_PRIMARY = createUniqueKey(AlarmDefinition.ALARM_DEFINITION, AlarmDefinition.ALARM_DEFINITION.ID);
		public static final UniqueKey<AlarmDefinitionSeverityRecord> KEY_ALARM_DEFINITION_SEVERITY_PRIMARY = createUniqueKey(AlarmDefinitionSeverity.ALARM_DEFINITION_SEVERITY, AlarmDefinitionSeverity.ALARM_DEFINITION_SEVERITY.NAME);
		public static final UniqueKey<AlarmMetricRecord> KEY_ALARM_METRIC_PRIMARY = createUniqueKey(AlarmMetric.ALARM_METRIC, AlarmMetric.ALARM_METRIC.ALARM_ID, AlarmMetric.ALARM_METRIC.METRIC_DEFINITION_DIMENSIONS_ID);
		public static final UniqueKey<AlarmStateRecord> KEY_ALARM_STATE_PRIMARY = createUniqueKey(AlarmState.ALARM_STATE, AlarmState.ALARM_STATE.NAME);
		public static final UniqueKey<EventTransformRecord> KEY_EVENT_TRANSFORM_PRIMARY = createUniqueKey(EventTransform.EVENT_TRANSFORM, EventTransform.EVENT_TRANSFORM.ID);
		public static final UniqueKey<EventTransformRecord> KEY_EVENT_TRANSFORM_TENANT_NAME = createUniqueKey(EventTransform.EVENT_TRANSFORM, EventTransform.EVENT_TRANSFORM.TENANT_ID, EventTransform.EVENT_TRANSFORM.NAME);
		public static final UniqueKey<MetricDefinitionRecord> KEY_METRIC_DEFINITION_PRIMARY = createUniqueKey(MetricDefinition.METRIC_DEFINITION, MetricDefinition.METRIC_DEFINITION.ID);
		public static final UniqueKey<MetricDefinitionDimensionsRecord> KEY_METRIC_DEFINITION_DIMENSIONS_PRIMARY = createUniqueKey(MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS, MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS.ID);
		public static final UniqueKey<MetricDimensionRecord> KEY_METRIC_DIMENSION_METRIC_DIMENSION_KEY = createUniqueKey(MetricDimension.METRIC_DIMENSION, MetricDimension.METRIC_DIMENSION.DIMENSION_SET_ID, MetricDimension.METRIC_DIMENSION.NAME);
		public static final UniqueKey<NotificationMethodRecord> KEY_NOTIFICATION_METHOD_PRIMARY = createUniqueKey(NotificationMethod.NOTIFICATION_METHOD, NotificationMethod.NOTIFICATION_METHOD.ID);
		public static final UniqueKey<NotificationMethodTypeRecord> KEY_NOTIFICATION_METHOD_TYPE_PRIMARY = createUniqueKey(NotificationMethodType.NOTIFICATION_METHOD_TYPE, NotificationMethodType.NOTIFICATION_METHOD_TYPE.NAME);
		public static final UniqueKey<SchemaMigrationsRecord> KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS = createUniqueKey(SchemaMigrations.SCHEMA_MIGRATIONS, SchemaMigrations.SCHEMA_MIGRATIONS.VERSION);
		public static final UniqueKey<StreamActionsRecord> KEY_STREAM_ACTIONS_PRIMARY = createUniqueKey(StreamActions.STREAM_ACTIONS, StreamActions.STREAM_ACTIONS.STREAM_DEFINITION_ID, StreamActions.STREAM_ACTIONS.ACTION_ID, StreamActions.STREAM_ACTIONS.ACTION_TYPE);
		public static final UniqueKey<StreamActionsActionTypeRecord> KEY_STREAM_ACTIONS_ACTION_TYPE_PRIMARY = createUniqueKey(StreamActionsActionType.STREAM_ACTIONS_ACTION_TYPE, StreamActionsActionType.STREAM_ACTIONS_ACTION_TYPE.NAME);
		public static final UniqueKey<StreamDefinitionRecord> KEY_STREAM_DEFINITION_PRIMARY = createUniqueKey(StreamDefinition.STREAM_DEFINITION, StreamDefinition.STREAM_DEFINITION.ID);
		public static final UniqueKey<StreamDefinitionRecord> KEY_STREAM_DEFINITION_TENANT_NAME = createUniqueKey(StreamDefinition.STREAM_DEFINITION, StreamDefinition.STREAM_DEFINITION.TENANT_ID, StreamDefinition.STREAM_DEFINITION.NAME);
		public static final UniqueKey<SubAlarmRecord> KEY_SUB_ALARM_PRIMARY = createUniqueKey(SubAlarm.SUB_ALARM, SubAlarm.SUB_ALARM.ID);
		public static final UniqueKey<SubAlarmDefinitionRecord> KEY_SUB_ALARM_DEFINITION_PRIMARY = createUniqueKey(SubAlarmDefinition.SUB_ALARM_DEFINITION, SubAlarmDefinition.SUB_ALARM_DEFINITION.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AlarmActionRecord, NotificationMethodRecord> FK_ALARM_ACTION_NOTIFICATION_METHOD_ID = createForeignKey(monasca.common.jooq.Keys.KEY_NOTIFICATION_METHOD_PRIMARY, AlarmAction.ALARM_ACTION, AlarmAction.ALARM_ACTION.ACTION_ID);
		public static final ForeignKey<AlarmMetricRecord, AlarmRecord> FK_ALARM_ID = createForeignKey(monasca.common.jooq.Keys.KEY_ALARM_PRIMARY, AlarmMetric.ALARM_METRIC, AlarmMetric.ALARM_METRIC.ALARM_ID);
		public static final ForeignKey<StreamActionsRecord, NotificationMethodRecord> FK_STREAM_ACTION_NOTIFICATION_METHOD_ID = createForeignKey(monasca.common.jooq.Keys.KEY_NOTIFICATION_METHOD_PRIMARY, StreamActions.STREAM_ACTIONS, StreamActions.STREAM_ACTIONS.ACTION_ID);
		public static final ForeignKey<SubAlarmRecord, AlarmRecord> FK_SUB_ALARM = createForeignKey(monasca.common.jooq.Keys.KEY_ALARM_PRIMARY, SubAlarm.SUB_ALARM, SubAlarm.SUB_ALARM.ALARM_ID);
		public static final ForeignKey<SubAlarmRecord, SubAlarmDefinitionRecord> FK_SUB_ALARM_EXPR = createForeignKey(monasca.common.jooq.Keys.KEY_SUB_ALARM_DEFINITION_PRIMARY, SubAlarm.SUB_ALARM, SubAlarm.SUB_ALARM.SUB_EXPRESSION_ID);
		public static final ForeignKey<SubAlarmDefinitionRecord, AlarmDefinitionRecord> FK_SUB_ALARM_DEFINITION = createForeignKey(monasca.common.jooq.Keys.KEY_ALARM_DEFINITION_PRIMARY, SubAlarmDefinition.SUB_ALARM_DEFINITION, SubAlarmDefinition.SUB_ALARM_DEFINITION.ALARM_DEFINITION_ID);
		public static final ForeignKey<SubAlarmDefinitionDimensionRecord, SubAlarmDefinitionRecord> FK_SUB_ALARM_DEFINITION_DIMENSION = createForeignKey(monasca.common.jooq.Keys.KEY_SUB_ALARM_DEFINITION_PRIMARY, SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION, SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION.SUB_ALARM_DEFINITION_ID);
	}
}
