/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import monasca.common.jooq.tables.Alarm;
import monasca.common.jooq.tables.AlarmAction;
import monasca.common.jooq.tables.AlarmDefinition;
import monasca.common.jooq.tables.AlarmDefinitionSeverity;
import monasca.common.jooq.tables.AlarmMetric;
import monasca.common.jooq.tables.AlarmState;
import monasca.common.jooq.tables.EventTransform;
import monasca.common.jooq.tables.MetricDefinition;
import monasca.common.jooq.tables.MetricDefinitionDimensions;
import monasca.common.jooq.tables.MetricDimension;
import monasca.common.jooq.tables.NotificationMethod;
import monasca.common.jooq.tables.NotificationMethodType;
import monasca.common.jooq.tables.SchemaMigrations;
import monasca.common.jooq.tables.StreamActions;
import monasca.common.jooq.tables.StreamActionsActionType;
import monasca.common.jooq.tables.StreamDefinition;
import monasca.common.jooq.tables.SubAlarm;
import monasca.common.jooq.tables.SubAlarmDefinition;
import monasca.common.jooq.tables.SubAlarmDefinitionDimension;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mon extends SchemaImpl {

	private static final long serialVersionUID = 708842263;

	/**
	 * The reference instance of <code>mon</code>
	 */
	public static final Mon MON = new Mon();

	/**
	 * No further instances allowed
	 */
	private Mon() {
		super("mon");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Alarm.ALARM,
			AlarmAction.ALARM_ACTION,
			AlarmDefinition.ALARM_DEFINITION,
			AlarmDefinitionSeverity.ALARM_DEFINITION_SEVERITY,
			AlarmMetric.ALARM_METRIC,
			AlarmState.ALARM_STATE,
			EventTransform.EVENT_TRANSFORM,
			MetricDefinition.METRIC_DEFINITION,
			MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS,
			MetricDimension.METRIC_DIMENSION,
			NotificationMethod.NOTIFICATION_METHOD,
			NotificationMethodType.NOTIFICATION_METHOD_TYPE,
			SchemaMigrations.SCHEMA_MIGRATIONS,
			StreamActions.STREAM_ACTIONS,
			StreamActionsActionType.STREAM_ACTIONS_ACTION_TYPE,
			StreamDefinition.STREAM_DEFINITION,
			SubAlarm.SUB_ALARM,
			SubAlarmDefinition.SUB_ALARM_DEFINITION,
			SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION);
	}
}
