/**
 * This class is generated by jOOQ
 */
package monasca.common.jooq;


import javax.annotation.Generated;

import monasca.common.jooq.tables.Alarm;
import monasca.common.jooq.tables.AlarmAction;
import monasca.common.jooq.tables.AlarmDefinition;
import monasca.common.jooq.tables.AlarmDefinitionSeverity;
import monasca.common.jooq.tables.AlarmMetric;
import monasca.common.jooq.tables.AlarmState;
import monasca.common.jooq.tables.EventTransform;
import monasca.common.jooq.tables.MetricDefinition;
import monasca.common.jooq.tables.MetricDefinitionDimensions;
import monasca.common.jooq.tables.MetricDimension;
import monasca.common.jooq.tables.NotificationMethod;
import monasca.common.jooq.tables.NotificationMethodType;
import monasca.common.jooq.tables.SchemaMigrations;
import monasca.common.jooq.tables.StreamActions;
import monasca.common.jooq.tables.StreamActionsActionType;
import monasca.common.jooq.tables.StreamDefinition;
import monasca.common.jooq.tables.SubAlarm;
import monasca.common.jooq.tables.SubAlarmDefinition;
import monasca.common.jooq.tables.SubAlarmDefinitionDimension;


/**
 * Convenience access to all tables in mon
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table mon.alarm
	 */
	public static final Alarm ALARM = monasca.common.jooq.tables.Alarm.ALARM;

	/**
	 * The table mon.alarm_action
	 */
	public static final AlarmAction ALARM_ACTION = monasca.common.jooq.tables.AlarmAction.ALARM_ACTION;

	/**
	 * The table mon.alarm_definition
	 */
	public static final AlarmDefinition ALARM_DEFINITION = monasca.common.jooq.tables.AlarmDefinition.ALARM_DEFINITION;

	/**
	 * The table mon.alarm_definition_severity
	 */
	public static final AlarmDefinitionSeverity ALARM_DEFINITION_SEVERITY = monasca.common.jooq.tables.AlarmDefinitionSeverity.ALARM_DEFINITION_SEVERITY;

	/**
	 * The table mon.alarm_metric
	 */
	public static final AlarmMetric ALARM_METRIC = monasca.common.jooq.tables.AlarmMetric.ALARM_METRIC;

	/**
	 * The table mon.alarm_state
	 */
	public static final AlarmState ALARM_STATE = monasca.common.jooq.tables.AlarmState.ALARM_STATE;

	/**
	 * The table mon.event_transform
	 */
	public static final EventTransform EVENT_TRANSFORM = monasca.common.jooq.tables.EventTransform.EVENT_TRANSFORM;

	/**
	 * The table mon.metric_definition
	 */
	public static final MetricDefinition METRIC_DEFINITION = monasca.common.jooq.tables.MetricDefinition.METRIC_DEFINITION;

	/**
	 * The table mon.metric_definition_dimensions
	 */
	public static final MetricDefinitionDimensions METRIC_DEFINITION_DIMENSIONS = monasca.common.jooq.tables.MetricDefinitionDimensions.METRIC_DEFINITION_DIMENSIONS;

	/**
	 * PRIMARY KEY (`id`)
	 */
	public static final MetricDimension METRIC_DIMENSION = monasca.common.jooq.tables.MetricDimension.METRIC_DIMENSION;

	/**
	 * The table mon.notification_method
	 */
	public static final NotificationMethod NOTIFICATION_METHOD = monasca.common.jooq.tables.NotificationMethod.NOTIFICATION_METHOD;

	/**
	 * The table mon.notification_method_type
	 */
	public static final NotificationMethodType NOTIFICATION_METHOD_TYPE = monasca.common.jooq.tables.NotificationMethodType.NOTIFICATION_METHOD_TYPE;

	/**
	 * The table mon.schema_migrations
	 */
	public static final SchemaMigrations SCHEMA_MIGRATIONS = monasca.common.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS;

	/**
	 * The table mon.stream_actions
	 */
	public static final StreamActions STREAM_ACTIONS = monasca.common.jooq.tables.StreamActions.STREAM_ACTIONS;

	/**
	 * The table mon.stream_actions_action_type
	 */
	public static final StreamActionsActionType STREAM_ACTIONS_ACTION_TYPE = monasca.common.jooq.tables.StreamActionsActionType.STREAM_ACTIONS_ACTION_TYPE;

	/**
	 * The table mon.stream_definition
	 */
	public static final StreamDefinition STREAM_DEFINITION = monasca.common.jooq.tables.StreamDefinition.STREAM_DEFINITION;

	/**
	 * The table mon.sub_alarm
	 */
	public static final SubAlarm SUB_ALARM = monasca.common.jooq.tables.SubAlarm.SUB_ALARM;

	/**
	 * The table mon.sub_alarm_definition
	 */
	public static final SubAlarmDefinition SUB_ALARM_DEFINITION = monasca.common.jooq.tables.SubAlarmDefinition.SUB_ALARM_DEFINITION;

	/**
	 * The table mon.sub_alarm_definition_dimension
	 */
	public static final SubAlarmDefinitionDimension SUB_ALARM_DEFINITION_DIMENSION = monasca.common.jooq.tables.SubAlarmDefinitionDimension.SUB_ALARM_DEFINITION_DIMENSION;
}
